---
- name: copy
  become: true
  copy:
    src:  ~/project/artifact.tar.gz
    dest: /root/artifact.tar.gz 

- name: start server
  become: true
  shell: |
    tar xzf artifact.tar.gz 
    npm install
    npm run build
    pm2 start npm -- start